### ISSUE TITLE
Cannot save 8bit grayscale image

### ISSUE THREAD

**Issue by yglukhov** [jangko/nimBMP#1]
``` nim
import streams, nimBMP
let str = newString(10 * 20) # width = 10, height = 20, all pixels are 0.
var s = newFileStream("out.bmp", fmWrite)
s.encodeBMP(str, 10, 20, 8) # Should produce black image, right?
s.close()
```

```
test.nim(4)              test
nimBMP.nim(765)          encodeBMP
nimBMP.nim(734)          autoChooseColor
nimBMP.nim(634)          countColors
system.nim(3335)         failedAssertImpl
system.nim(3327)         raiseAssert
system.nim(2527)         sysFatal
Error: unhandled exception: contains({24, 32}, bitsPerPixel)  [AssertionError]
```

**Comment by jangko** [comment]
nimBMP encoder accept uncompressed pixels, in RGB/A format, and each channel is 8 bit wide. **one pixel** is 24 bits or 32 bits as the exception suggested(a bit cryptic though).
rewrite the code:

``` nimrod
import streams, nimBMP
let str = newString(10 * 20 * 3) # width = 10, height = 20, all pixels are 0. RGB 24 bits
var s = newFileStream("out.bmp", fmWrite)
s.encodeBMP(str, 10, 20, 24) # Should produce black image, right? yes, but need 24 bits
s.close()
```

the internal algorithm then will decide the best compression and palette that will be saved to file.

basically, nimBMP **encoder** accepts raw pixels 24/32 bits wide per pixel, and encode it to whatever format the algorithm choose.
the **decoder** work in reverse direction, accept whatever valid BMP format from file and produce raw pixels 24/32 bits wide per pixel.

thanks for the reminder anyway -> I need to write a better documentation for this

**Comment by yglukhov** [comment]
Ok thank you.
